;;; adwaita-dark-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from adwaita-dark-theme.el

(autoload 'adwaita-dark-theme-neotree-configuration-enable "adwaita-dark-theme" "\
Enable custom adwaita-dark configuration for use with neotree.")
(autoload 'adwaita-dark-theme-eldoc-frame-configuration-enable "adwaita-dark-theme" "\
Enable custom adwaita-dark configuration for use with eldoc-frame.")
(autoload 'adwaita-dark-theme-arrow-fringe-bmp-enable "adwaita-dark-theme" "\
Replace the default line continuation and line wrap arrows with custom bitmaps.")
(autoload 'adwaita-dark-theme-diff-hl-fringe-bmp-enable "adwaita-dark-theme" "\
Enable custom adwaita-dark fringe bitmaps for use with flymake.")
(autoload 'adwaita-dark-theme-flycheck-fringe-bmp-enable "adwaita-dark-theme" "\
Enable custom adwaita-dark fringe bitmaps for use with flycheck.")
(autoload 'adwaita-dark-theme-flymake-fringe-bmp-enable "adwaita-dark-theme" "\
Enable custom adwaita-dark fringe bitmaps for use with flymake.")
(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "adwaita-dark-theme" '("adwaita-dark"))

;;; End of scraped data

(provide 'adwaita-dark-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; adwaita-dark-theme-autoloads.el ends here
